[package]
name = "validator-reward-history"
version = "0.1.0"
edition = "2021"


[dependencies]
solana-client = "1.9.9"
solana-sdk = "1.9.9"
clap = { version = "3.1.6", features = ["derive"] }
chrono = "0.4.19"
csv = "1.1.6"
